const motivationMessage = [
  "You are resilient, and each challenge is shaping you into a stronger professional.",
  "You radiate positive energy that attracts supportive people and great opportunities.",
  "Let go of worry and focus on what you can control.",
  "You are qualified, capable, and bring unique value to every role you apply for.",
  "You welcome guidance, insight, and signs that help you stay on the right path.",
  "Your next job will bring joy, growth, and inspiration into your life.",
  "Be grateful for the lessons and experiences you're gaining right now.",
  "You are more than enough — you deserve a fulfilling and meaningful career.",
  "Trust the timing of your career path — everything is unfolding as it should.",
  "You are open to opportunities you may not have imagined but are perfect for you.",
  "You are clear about what you want, and you’re attracting roles that align with your goals.",
  "Rejections are not failures — they’re redirections toward something better.",
  "Each day brings fresh energy, hope, and purpose.",
  "Every application you send gets you closer to the job that’s meant for you.",
  "Choose patience and persistence over pressure and panic.",
  "You can stay optimistic and open-hearted through this process.",
  "Your skills, experience, and passion make you a strong candidate.",
  "The right job is searching for you too.",
  "You are growing with each step of this journey.",
  "This process is revealing more about who you are and what you truly want.",
  "You have everything you need within you to succeed.",
  "The right people recognize your potential and value.",
  "You are not behind — you are right on time for your journey.",
  "Your dedication is planting seeds for future success.",
  "You attract mentors, colleagues, and opportunities that help you thrive.",
  "You are allowed to rest without guilt — rest is part of progress.",
  "Even on hard days, you are making meaningful progress.",
  "You bring fresh ideas and valuable energy to every team.",
  "You deserve a job that makes you feel valued and inspired.",
  "You are becoming the professional you once dreamed of being.",
  "You are more prepared than you think.",
  "Opportunities are making their way to you right now.",
  "You are capable of handling whatever comes next.",
  "You’re not just finding a job — you’re building your future.",
  "You deserve to work in an environment that respects and supports you.",
  "The skills you're building now are preparing you for the job you want.",
  "You have overcome challenges before — you’ll overcome this too.",
  "Your energy is magnetic — people want to work with you.",
  "You are showing up for yourself every day, and that matters.",
  "You are creating a career you’ll be proud of.",
];

export default motivationMessage;
